name: build and upload
on:
  push:
    branches:
      - "master"

jobs:
  build_upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: build
        run: ./make.sh
      - name: version
        run: echo "::set-output name=version::$(./ytarchive -V)"
        id: version
      - name: tag
        run: echo "::set-output name=tag::$(git rev-parse --short HEAD)"
        id: tag
      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.tag.outputs.tag }}
          prerelease: true
          title: ${{ steps.version.outputs.version }}
          files: |
            ytarchive_linux_amd64.zip
            ytarchive_windows_amd64.zip
            SHA2-256SUMS

